name: Quality Check
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"  # Set Python version 
      # - uses: chartboost/ruff-action@v1
      # - run: ruff check p5/*.py
      - run: python -m pip install -r requirements.txt
      - run: black p5/*.py
      - run: ruff check p5/*.py --fix
      - run: pyright p5/*.py
      - run: git add --all
      - run: git commit -m "QualityCheck Fixed code using ruff in CI/CD"
      - run: git push