name: Quality Check
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"  # Set Python version 
      # - uses: chartboost/ruff-action@v1
      # - run: ruff check p5/*.py
      - name: Install Python requirements
        run: python -m pip install -r requirements.txt
      - name: Formatting code
        run: black p5/*.py
      - name: Linting Code
        run: |
          ruff check p5/*.py --fix
          pyright p5/*.py
      - name: Update Git repository
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "QualityCheck Fixed code using ruff in CI/CD"
          git push