name: Ruff
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: chartboost/ruff-action@v1
      - run: ruff check p5/*.py